### PR TITLE
remove unnecessary classes

### PR DESCRIPTION
**Pull request by smallgod**
pushing string3 implementation for review

### CODE REVIEW

**Comment by smallgod** [comment]
draft

**Comment by ssmusoke** [comment]
@smallgod  Add a .gitignore example is here https://github.com/METS-Programme/openmrs-module-ugandaemr/blob/master/.gitignore

**Comment by ssmusoke** [comment]
@smallgod you have not worked on my comment which reduces the number of files to work with

**Comment by smallgod** [comment]
@ssmusoke let me please get more clarity from you tomorrow concerning this.

**Comment by smallgod** [comment]
> @smallgod you have not worked on my comment which reduces the number of files to work with

@ssmusoke let me please get more clarity from you tomorrow concerning this.

**Comment by smallgod** [comment]
> @smallgod Add a .gitignore example is here https://github.com/METS-Programme/openmrs-module-ugandaemr/blob/master/.gitignore

@ssmusoke In the PR I tagged you in, I added the .gitignore file. Thanks.

**Comment by smallgod** [comment]
> > @smallgod you have not worked on my comment which reduces the number of files to work with
> 
> @ssmusoke let me please get more clarity from you tomorrow concerning this.

@ssmusoke Just incase you were talking about the .gitignore file. I added it, thanks.

**Comment by ssmusoke** [comment]
@smallgod you need to delete the extra files in the target directory in both the api and omod folders

**Comment by smallgod** [comment]
consider new pull request

**Pull request closed without merging**
